baseURL = "https://gingkowriter.com/"
languageCode = "en-us"
title = ""
theme = "hugo-gingko"
[menu]
  [[menu.mainmenu]]
    identifier = "faq"
    name = "FAQ"
    url = "https://docs.gingkowriter.com"
  [[menu.mainmenu]]
    identifier = "login"
    name = "Login"
    url = "https://app.gingkowriter.com/login"
